# config.yaml

# 路径配置
input_dir: "/home/wtian/data/illumina_WGS/prepare_for_SRY"  # 存放所有样本的双端测序 FASTQ 文件的目录
sample_list: "sample_list.txt"  # 样本列表文件
output_dir: "results"  # 输出文件存储的主目录
reference: "/home/wtian/data/reference/GRCh38/HZAU_cohort_wdy/annotation_paired/GRCh38.NCBI.no_alt.no_contigs.toUCSC.fasta"  # 参考基因组路径
gatk_bundle: "/home/wtian/data/resource/gatk"  # GATK 资源包目录路径

# GATK 资源文件 - 替换为完整路径
resources:
  hapmap: "/home/wtian/data/resource/gatk/hg38_v0_hapmap_3.3.hg38.vcf"
  omni: "/home/wtian/data/resource/gatk/hg38_v0_1000G_omni2.5.hg38.vcf"
  phase1_1000G: "/home/wtian/data/resource/gatk/hg38_v0_1000G_phase1.snps.high_confidence.hg38.vcf"
  dbsnp: "/home/wtian/data/resource/gatk/hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"
  mills: "/home/wtian/data/resource/gatk/hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf"

# 其他参数
threads: 10  # 默认使用的线程数
